output:
  - adapter: influxdb
    host: 10.70.181.211,127.0.0.1  #多个用","分隔
    username: root
    password: 1qaz2wsx
    database: "oc_data_stats_test"

output:
  - series_name: 'applog_service_test'
    desc: "统计service_key"
    cron: "* * * * *"
    runtime:
      interval: 60
      delay_time: 300
      cache: true
    hosts:
      - adapter: "oracle"
        host: "10.78.136.12"
        port: 1521
        version: "12c"
        username: "logmgr"
        password: "logmgr"
        database: "applog"
        sql_group:
          - sql: "select system_domain, subsystem_domain, app_server_name, substr(service_key,38) service_key, sys_op_id, op_id, op_code, op_org_id, op_region_code, op_county_code, op_district_code, op_province_code, channel_type, client_ip, bill_id, (EXTRACT(MINUTE FROM op_end_date - op_start_date) * 60000 +EXTRACT(SECOND FROM op_end_date - op_start_date) * 1000) MS, host_ip, log_type from logmgr.osb_srv_oplog partition(p$beginday) where log_type='A_BG_INTF_SRVCALL_OSB' and op_date >= to_date('$begin','yyyy-mm-dd hh24:mi:ss') and op_date < to_date('$end','yyyy-mm-dd hh24:mi:ss')"
            options:
              $beginmonth: "%Y%m"
              $beginday: "%Y%m%d"
              $begin: "%Y-%m-%d %H:%M:00"
              $end: "%Y-%m-%d %H:%M:00"
            cache_set:
              tname: "service_key_data"
              field_set:
                system_domain: "string"
                subsystem_domain: "string"
                app_server_name: "sring"
                service_key: "string"
                sys_op_id: "string"
                op_id: "string"
                op_code: "string"
                op_org_id: "string"
                op_region_code: "string"
                op_county_code: "string"
                op_district_code: "string"
                op_province_code: "string"
                channel_type: "string"
                client_ip: "string"
                bill_id: "string"
                ms: "integer"
                host_ip: "string"
                log_type: "string"
              cache_sql:
                - series_name: "test.first"
                  sql: "select round(avg(ms)) as ms ,count(*) as count, service_key from $tname group by service_key"
                - series_name: "test.two"
                  sql: "select round(avg(ms)) as ms ,count(*) as count,'SUM' as service_key from $tname"
